# Generated by Django 2.2 on 2019-04-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataToBe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.IntegerField()),
                ('field_2', models.CharField(max_length=50)),
                ('field_3', models.FloatField()),
                ('field_4', models.FloatField()),
                ('field_5', models.CharField(max_length=50)),
                ('field_6', models.IntegerField()),
            ],
        ),
    ]
