# Generated by Django 2.2 on 2019-04-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elastic_api', '0003_auto_20190430_0151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
